# Orbit Data Randomizer

In [8]:
import numpy as np
import pandas as pd
from matplotlib import pyplot
from sklearn import preprocessing
from sklearn.datasets import fetch_openml

## Loading the dataset

In [9]:
df = pd.read_csv('orbit.csv')
df = df.sample(frac=1, random_state=123).reset_index(drop=True)
print(df.shape)
#df.head(2500).to_csv('shortenedorbit.csv', index=False)

C:\Users\andromeda\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (7,8,9,10,11,12,14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

(1048121, 35)

In [10]:
possibleLabels = df.Orbit_type.value_counts()
possibleLabels

MBA                                           951452
Hungaria                                       25449
Object with perihelion distance < 1.665 AU     16810
Apollo                                         12610
Phocaea                                        11400
Amor                                           10373
Jupiter Trojan                                  9423
Hilda                                           4643
Distant Object                                  4026
Aten                                            1885
Atira                                             50
Name: Orbit_type, dtype: int64

In [11]:
df.head(25000)

,NEO_flag,One_km_NEO_flag,PHA_flag,H,G,Num_obs,rms,U,Arc_years,Perturbers,...,Computer,Hex_flags,Last_obs,Tp,Orbital_period,Perihelion_dist,Aphelion_dist,Semilatus_rectum,Synodic_period,Orbit_type
0,NaN,NaN,NaN,16.80,0.15,121.0,0.22,0.0,2009-2020,M-v,...,MPCLINUX,0400,2020-12-05,2.459269e+06,5.330613,2.674377,3.428689,1.502459,1.230914,MBA
1,NaN,NaN,NaN,16.00,0.15,144.0,0.33,0,2006-2019,M-v,...,MPCLINUX,0000,2019-04-06,2.459310e+06,4.288446,2.323043,2.956098,1.300807,1.304095,MBA
2,NaN,NaN,NaN,16.80,0.15,171.0,0.32,0.0,2009-2021,M-v,...,MPCLINUX,0400,2021-01-07,2.459135e+06,4.582282,2.148507,3.369106,1.311898,1.279152,MBA
3,NaN,NaN,NaN,17.00,0.15,116.0,0.25,0.0,2004-2019,M-v,...,Williams,0000,2019-12-21,2.459808e+06,4.475341,2.555393,2.876036,1.353125,1.287742,MBA
4,NaN,NaN,NaN,17.80,0.15,156.0,0.30,0,2006-2021,M-v,...,MPCLINUX,0400,2021-01-06,2.459163e+06,3.629309,1.843977,2.879327,1.124089,1.380328,MBA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,NaN,NaN,NaN,17.00,0.15,192.0,0.39,0,2003-2020,M-v,...,MPCW,0000,2020-01-28,2.459667e+06,3.564286,1.891282,2.775438,1.124802,1.389972,MBA
24996,NaN,NaN,NaN,18.80,0.15,96.0,0.30,1.0,2012-2020,M-v,...,MPCLINUX,0000,2020-12-12,2.459137e+06,4.144424,1.781869,3.378405,1.166581,1.318023,MBA
24997,NaN,NaN,NaN,14.00,0.15,857.0,0.41,0,1994-2020,M-v,...,MPCW,0000,2020-01-28,2.459129e+06,5.633110,2.453032,3.878791,1.502695,1.215838,MBA
24998,NaN,NaN,NaN,17.20,0.15,115.0,0.29,0,2010-2020,M-v,...,MPCW,0000,2020-01-19,2.458726e+06,4.266189,2.112224,3.148635,1.264171,1.306167,MBA
24999,NaN,NaN,NaN,16.15,0.15,229.0,0.59,0,2000-2020,M-v,...,Pan,0000,2020-05-16,2.459798e+06,5.492472,2.526955,3.699037,1.501335,1.222595,MBA